### ISSUE TITLE
v3.14.2 - Admin Portal Alarms page - issue with 29th Feb - Leap Year & using wrong year?!

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#151]
It appears that OpenWIS Admin Portal in v3.14.2 on our Dev system cannot cope with the 29th of Feb in a Leap Year. 
But.... I notice that the system seems to think it is 2015 when it knows that it is 2016. So it is correct to raise an error as 29th Feb doesn't exist in 2015. But why does it think it's 2015? and would it make a difference even if it did have the correct year?

The result of this issue causes the Recent Events window to be empty, but a search can still find events for 29th Feb 2016.
I wonder what else this might affect.
(This bug also occurs in v3.10 and and v3.12 and has probably always been there)

ERROR shown in openwis.log :
(the error shows when opening admin portal alerts page)

2016-02-29 11:13:52,033 ERROR [jeeves.service] - Exception when executing service
2016-02-29 11:13:52,033 ERROR [jeeves.service] -  (C) Exc : javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: "2015-02-29T11:13:51.909Z" is not a valid representation of an XML Gregorian Calendar value.
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: "2015-02-29T11:13:51.909Z" is not a valid representation of an XML Gregorian Calendar value.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:111)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:129)
        at com.sun.proxy.$Proxy45.getRecentEventsSorted(Unknown Source)
        at org.openwis.metadataportal.services.management.RecentEvents.getRecentEvents(RecentEvents.java:191)
        at org.openwis.metadataportal.services.management.RecentEvents.exec(RecentEvents.java:145)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)
2016-02-29 11:13:52,035 ERROR [jeeves.service] - Raised exception while executing service
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: "2015-02-29T11:13:51.909Z" is not a valid representation of an XML Gregorian Calendar value.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:111)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:129)
        at com.sun.proxy.$Proxy45.getRecentEventsSorted(Unknown Source)
        at org.openwis.metadataportal.services.management.RecentEvents.getRecentEvents(RecentEvents.java:191)
        at org.openwis.metadataportal.services.management.RecentEvents.exec(RecentEvents.java:145)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)

**Comment by lmika-bom** [comment]
Hopefully by the next leap year, OpenWIS 3.x would have been retired.

**Comment by rogers492** [comment]
ok, closed.

**Comment by woollattd** [comment]
reopened since OpenWIS v3.x is in maintenance mode for next 6 years so this still applies
