### ISSUE TITLE
Public Dissemination issue - Save button causes error

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#159]
when using the 'Save' button in the Public Dissemination window for an FTP or Mail deissemination an error occurs
![mailsave](https://cloud.githubusercontent.com/assets/6514963/13875199/686eee62-ecf4-11e5-850d-df24a8ba4cbf.jpg)

**extract from openwis.log**
2016-03-18 10:22:19,113 INFO  [jeeves.service] -  -> dispatch ended for : xml.get.home.page.last.products
2016-03-18 10:22:49,184 INFO  [jeeves.request] - ==========================================================
2016-03-18 10:22:49,184 INFO  [jeeves.request] - HTML Request (from ??.??.??.??) : /openwis-user-portal/srv/en/xml.save.favorite.dissemination.parameter
2016-03-18 10:22:49,184 INFO  [jeeves.service] - Dispatching : xml.save.favorite.dissemination.parameter
2016-03-18 10:22:49,209 ERROR [jeeves.service] - Exception when executing service
2016-03-18 10:22:49,209 ERROR [jeeves.service] -  (C) Exc : org.openwis.securityservice.UserManagementException_Exception: Fault occurred while processing.
org.openwis.securityservice.UserManagementException_Exception: Fault occurred while processing.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:129)
        at com.sun.proxy.$Proxy64.addOrUpdateEmailForDisseminationParameters(Unknown Source)
        at org.openwis.metadataportal.services.dissemination.SaveFavoriteDisseminationParameter.exec(SaveFavoriteDisseminationParameter.java:48)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)
2016-03-18 10:22:49,210 ERROR [jeeves.service] - Raised exception while executing service
org.openwis.securityservice.UserManagementException_Exception: Fault occurred while processing.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:130)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:129)
        at com.sun.proxy.$Proxy64.addOrUpdateEmailForDisseminationParameters(Unknown Source)
        at org.openwis.metadataportal.services.dissemination.SaveFavoriteDisseminationParameter.exec(SaveFavoriteDisseminationParameter.java:48)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)

**Comment by lmika-bom** [comment]
This might be a configuration issue.  Please check if this is still occurring.

**Comment by rogers492** [comment]
Ok, closed. Will raise again if it comes up in testing.

**Comment by woollattd** [comment]
reopened since OpenWIS v3.x is in maintenance mode for next 6 years so this still applies
