### ISSUE TITLE
Error in "Track my Requests" on User Portal

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#236]
In the User Portal, under 'My Account'>'Track my requests'>'Requests' there is an Error produced when trying to view an 'old' request shown in the 'User alarms' table.
(note- the requests can be viewed should an alert happen on the day they are requested).

![up-error](https://cloud.githubusercontent.com/assets/6514963/20519359/8a388d0e-b09a-11e6-9a95-42f85575489b.jpg)

This is not particularly helpful as there is nothing in the table to show which data wasn't delivered. apart from an ID.
Also if a record of failure is to be listed then why not keep the details?
I notice the 'Track my local requests' table has only the current entry. 
This table is where we might link the ID from the previous table to find out which data the Alarm related to - but the others don't appear here.
Shouldn't these previous ones be listed as well? is there a time limit on this? I hope it's more than 3 days!
(it really is a pain that these show as complete - when they are not)

the openwis.log shows this for the Error:

2016-11-22 09:39:07,563 INFO  [jeeves.request] - ==========================================================
2016-11-22 09:39:07,564 INFO  [jeeves.request] - HTML Request (from 10.144.146.34) : /openwis-user-portal/srv/en/xml.adhoc.get
2016-11-22 09:39:07,564 INFO  [jeeves.service] - Dispatching : xml.adhoc.get
2016-11-22 09:39:07,590 ERROR [jeeves.service] - Exception when executing service
2016-11-22 09:39:07,590 ERROR [jeeves.service] -  (C) Exc : java.lang.NullPointerException
java.lang.NullPointerException
        at org.openwis.metadataportal.services.request.dto.follow.AdhocDTO.adhocProcessedRequestToDTO(AdhocDTO.java:80)
        at org.openwis.metadataportal.services.request.AdhocGet.exec(AdhocGet.java:42)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)
2016-11-22 09:39:07,590 ERROR [jeeves.service] - Raised exception while executing service
java.lang.NullPointerException
        at org.openwis.metadataportal.services.request.dto.follow.AdhocDTO.adhocProcessedRequestToDTO(AdhocDTO.java:80)
        at org.openwis.metadataportal.services.request.AdhocGet.exec(AdhocGet.java:42)
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:236)
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:141)
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:425)
        at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
        at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
        at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:722)

**Comment by jude2018** [comment]
Steve Olsen to feedback on whether this can be pickeds up by NWS @solson-nws
