### ISSUE TITLE
Java8 Compatibility

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis#261]
Using Java-8 and Maven-3 I was able to build OpenAM-13.0.0 and OpenDJ-3.0.0 plus all of OpenWIS.  Look at [open-dj-am-install-scripts issue](https://github.com/OpenWIS/open-dj-am-install-scripts/issues/8) for the OpenAM and OpenDJ build.  Authentication system deployment was successful, and I was able to setup the Federation, however the portals had a Java Servelet problem and did not open.  To test the Federation, I simply changed the server's Java version back to Java-7 and the portals worked and authenticated correctly.

This looks like something in the Spring framework from GeoNetwork that is not compatible with Java-8

**Comment by mgiannoni** [comment]
Here is a Portal Deployment Exception:

> 2017-05-18 16:42:20,623 ERROR [jeeves.engine] -    Handler   : org.fao.geonet.Geonetwork
> 2017-05-18 16:42:20,624 ERROR [jeeves.engine] -    Exception : org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML  
> document from class path resource [JZkitApplicationContext.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan''
>  and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher
> 2017-05-18 16:42:20,624 ERROR [jeeves.engine] -    Message   : Unexpected exception parsing XML document from class path resource [JZkitApplicationContext.xml];;
>  nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.Coo
> mponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher
> 2017-05-18 16:42:20,624 ERROR [jeeves.engine] -    Stack     : org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML  
> document from class path resource [JZkitApplicationContext.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan''
>  and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342)
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310)
>         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:143)
>         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:178)
>         at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:149)
> 
> 
> Caused by: java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScaa
> nBeanDefinitionParser] are only available on JDK 1.5 and higher
>         at org.springframework.context.config.ContextNamespaceHandler$1.parse(ContextNamespaceHandler.java:65)
>         at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:69)
>         at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1253)
>         at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1243)
>         at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:135)
>         at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:92)
>

**Comment by mgiannoni** [comment]
Here is the Error when accessing the portal site

`2017-05-18 20:22:08,788 INFO  [jeeves.request] - HTML Request (from 140.90.90.106) : /openwis%2Dadmin%2Dportal/srv/en/main.home
2017-05-18 20:22:08,810 INFO  [jeeves.service] - Dispatching : main.home
2017-05-18 20:22:08,810 INFO  [jeeves.service] -    -> dispatching to output for : main.home
2017-05-18 20:22:08,818 ERROR [jeeves.service] - Raised exception while executing service
org.apache.jasper.JasperException: java.lang.NullPointerException
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:549)
`

`Caused by: java.lang.NullPointerException
	at org.apache.jsp.jsp.admin_jsp._jspService(admin_jsp.java:115)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
`

**Comment by dimipapadeas** [comment]
Dear @mgiannoni ,
OpenWIS v3 is built using maven 2.2.1 and Java 7.
You can find a comrehensive installation guide [here](https://github.com/OpenWIS/openwis/wiki/v3.14.5.1-Deployment-Instructions)

Please let me know if you have any other questions.

**Comment by mgiannoni** [comment]
See Issue(s): #274 #272 #273
