### ISSUE TITLE
New user creation errors on OpenWIS admin portal and issues related to BlacklistInfo; and staging post download related issue

### ISSUE THREAD

**Issue by zhangz555** [OpenWIS/openwis#304]
we encounter new user creation errors when using admin portal. More specifically, we are not able to add a new user without an error from the Blacklist module, and the Blacklist Info table remains empty in the database. We are migrating OpenWIS 3.14.9 from wildfly8 + centos6 to wildfly 15 + centos 7. We find that OpenWIS 3.14.9 on wildfly8 + centos6 appears to also have the same problem. So there is no available OpenWIS 3.14.9 system that ever works correctly at all.

We will try fixing this issue.

Below are some error messages we found in wildfly logging:
2019-07-17 12:52:16,074 ERROR [org.jboss.as.ejb3.invocation] (default task-2) WFLYEJB0034: EJB Invocation failed on component BlacklistService for method public boolean org.openwis.datasource.server.service.impl.BlacklistServiceImpl.isUserBlacklisted(java.lang.String): javax.ejb.EJBException: java.lang.NumberFormatException: For input string: "NOT_FOUND"        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)        at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)        at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)        at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)        at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)        at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)        at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)

--

**Comment by zhangz555** [comment]
Any issues we find is that User Portal does not reflect the availability of the data.   Normally these are listed in the "What's New" box, and you can select these directly from "What's New" and proceed to download fromt the Staging Post.   Alternatively, a search for "-Any-" can also bring up a list for download.    This part is not working and we have the following Error form the Tomcat User Portal. See below:
2019-07-25 23:30:27,421 INFO  [geonetwork.datamanager] - Found 200 new StopGap metadata.2019-07-25 23:30:27,432 ERROR [openwis.admin] - Could not synchronize stop gap datajava.lang.NullPointerException        at org.openwis.metadataportal.kernel.metadata.MetadataManager.createMetadataFromTemplate(MetadataManager.java:194)        at org.openwis.metadataportal.kernel.metadata.ProductMetadataManager.synchronizeStopGapMetadata(ProductMetadataManager.java:165)        at org.fao.geonet.Geonetwork$1.run(Geonetwork.java:423)        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)        at java.lang.Thread.run(Thread.java:748)2019-07-25 23:31:27,434 INFO  [geonetwork.datamanager] - Found 200 new StopGap metadata.
--

**Comment by zhangz555** [comment]
We have fixed all these issues stated above. We will create a pull request.

**Comment by zhangz555** [comment]
a pull request is created for this issue. Github automatically combine this newly created pull request into the already existent pull request #303.

**Comment by solson-nws** [comment]
This ticket can be closed.  It was merged into master
