### ISSUE TITLE
Issues with OpenWIS 3.15 installation

### ISSUE THREAD

**Issue by solson-nws** [OpenWIS/openwis#353]
Creating a omnibus issue for NWS, MF, BOM and KMA to highlight any and all issues related with installing OpenWIS 3.15.  These issues are contributing to our inability to assess OpenWIS 3.15.  I would like to capture each issue with the install and whether or not that still remains an issue, or if those issues are resolved.  For those that are resolved, please indicate what steps were taken to overcome the issue.

@anuruddhaa @yvesgoupil @mgiannoni @JeyoungRyu :  Please provide your updates on this ticket

**Comment by mgiannoni** [comment]
### Populate LDAP Initialize Deployment Error

`------ Populate LDAP ------ 
[1] Initialize Deployment
[2] Populate LDAP
[3] Reset LDAP Users
[4] Reset LDAP Groups
[5] Reset LDAP Users And Groups
Choose one of the above values. (any other value to exit)
1
Initialize Deployment:
Deployment Name:
GISCTest
Administrator Login:
admin
Exception in thread "main" com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Can't find resource for bundle java.util.PropertyResourceBundle, key ldap_ssl Please see the server log to find more detail regarding exact cause of the failure.
	at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:116)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy33.checkUserNameExists(Unknown Source)
	at org.openwis.usermanagement.PopulateUser.initializeDeployment(PopulateUser.java:117)
	at org.openwis.usermanagement.PopulateUser.displayMenu(PopulateUser.java:46)
	at org.openwis.usermanagement.PopulateUser.main(PopulateUser.java:239)
`

Reproduced the same error for both 3.14.10 version and 3.15 version of the populate LDAP script. 
Observed the following error in the "openwis-security-service.log".  Notice the "Check User Name Exists".  PopulateLDAP is checking to ensure the supplied administrator user "admin" is new.  The check uses the OpenWIS SecurityService API to query the LDAP directory.   SO... this indicated the true error in in the SecurityService
[PopulateLDAP.zip](https://github.com/OpenWIS/openwis/files/6151083/PopulateLDAP.zip)
 module deployed in tomcat.

`2021-03-12 11:49:35,165 WARN  [org.apache.cxf.phase.PhaseInterceptorChain] - Application {http://securityservice.openwis.org/}UserManagementService#{http://securityservice.openwis.org/}checkUserNameExists has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Can't find resource for bundle java.util.PropertyResourceBundle, key ldap_ssl
        at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163)
        at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.createFault(AbstractJAXWSMethodInvoker.java:272)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129)
        at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:237)
        at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:69)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:75)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
`

**Comment by mgiannoni** [comment]
### OpenIdentityPlatform Not Integrated Into OpenWIS Portals

The OpenIdentityPlatform OpenAM 4.5.x  -or- 4.6.2 (current version) is not acutally upgraded in the base OpenWIS portal code.
Here the true API for the integration still remains coded to the ForgeRock (proprietary) closed source OpenAM 12.0.0 version.  To perform a successful build, an existing Maven cache populated with ForgeRock components is needed.  More significantly, any API changed implemented since the ForgeRock 12.0.0 release are missing from the portal integration.

openwis/openwis-metadataportal/openwis-portal/pom.xml

        
        <dependency>
            <groupId>org.forgerock.openam</groupId>
            <artifactId>openam-idpdiscovery</artifactId>
            <version>12.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.forgerock.openam</groupId>
            <artifactId>openam-federation-library</artifactId>
            <version>12.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.forgerock.openam</groupId>
            <artifactId>openam-shared</artifactId>
            <version>12.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.forgerock.openam</groupId>
            <artifactId>openam-saml2-schema</artifactId>
            <version>12.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>2.1.4</version>
        </dependency>

**Comment by yvesgoupil** [comment]
### Apache Solr 8.2 installation procedure is missing.
How do we install Solr 8.2 ?
How  do we configure Solr for Openwis 3.15 ?
The configuration files are present but there is no explanation about how to organize them in a 8.2 standalone Solr deployment:
[https://github.com/OpenWIS/openwis/tree/openwis-3.15/openwis-metadataportal/openwis-portal/src/main/config-solr](url)

**Comment by yvesgoupil** [comment]
### List of attributes for IDP assertions processing : Update missing for v3.15
The current version 3.14.10 list is :   

     OpenWISAddress=OpenWISAddress
     OpenWISAddressCity=OpenWISAddressCity
     OpenWISAddressZip=OpenWISAddressZip
     OpenWISAddressState=OpenWISAddressState
     OpenWISAddressCountry=OpenWISAddressCountry
     OpenWISClassOfService=OpenWISClassOfService
     OpenWISBackUps=OpenWISBackUps
     OpenWISProfile=OpenWISProfile
     isMemberOf=isMemberOf
     OpenWISNeedUserAccount=OpenWISNeedUserAccount
     cn=cn
     sn=sn
     givenname=givenname
     mail=mail

**Comment by solson-nws** [comment]
@remy-gibault :  Yves may have already reached out to you and/or Yannick.  Any thoughts on the list of issues presented here and thoughts on how to overcome these?

Steve

**Comment by mgiannoni** [comment]
Wildfly Startup Error:

server.log.2021-03-11:2021-03-11 08:31:04,425 ERROR [org.hibernate.tuple.entity.PojoEntityTuplizer] (ServerService Thread Pool -- 81) HHH000112: Getters of lazy classes cannot be final: org.openwis.management.entity.AlarmEvent.date
server.log.2021-03-11:2021-03-11 08:31:04,425 ERROR [org.hibernate.tuple.entity.PojoEntityTuplizer] (ServerService Thread Pool -- 81) HHH000112: Getters of lazy classes cannot be final: org.openwis.management.entity.AlarmEvent.message
server.log.2021-03-11:2021-03-11 08:31:04,426 ERROR [org.hibernate.tuple.entity.PojoEntityTuplizer] (ServerService Thread Pool -- 81) HHH000112: Getters of lazy classes cannot be final: org.openwis.management.entity.AlarmEvent.module
server.log.2021-03-11:2021-03-11 08:31:04,426 ERROR [org.hibernate.tuple.entity.PojoEntityTuplizer] (ServerService Thread Pool -- 81) HHH000112: Getters of lazy classes cannot be final: org.openwis.management.entity.AlarmEvent.severity
server.log.2021-03-11:2021-03-11 08:31:04,427 ERROR [org.hibernate.tuple.entity.PojoEntityTuplizer] (ServerService Thread Pool -- 81) HHH000112: Getters of lazy classes cannot be final: org.openwis.management.entity.AlarmEvent.source

**Comment by yvesgoupil** [comment]
### Dataservice wmo-ftp files ingestion errors in Wildfly server.log file.

For each file intended to be put in the GISC cache, arises this Dataservice Wildfly error:

`2021-03-25 10:59:01,890 ERROR [org.openwis.dataservice.util.CacheUtils] (Thread-55 (ActiveMQ-client-global-threads)) Failed to post incoming data queue message due to {}: javax.naming.NameNotFoundException: queue/IncomingDataQueue -- service jboss.naming.context.java.queue.IncomingDataQueue
    at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:106)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
    at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:237)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
    at javax.naming.InitialContext.lookup(InitialContext.java:417)
...`

The Dataservice problem stems from the fact that the current version corresponds to a DCPC and the ingestion of files in wmo-ftp format has not been tested, as unnecessary for a DCPC.

**Comment by yvesgoupil** [comment]
### User portal login test - Captcha error

There is a way to bypass the captcha process only for a dev deployment:

Replace the keys in openwis-metadataportal.properties by the following values:
`openwis.metadataportal.login.captcha.secretKey=xxx`
`openwis.metadataportal.login.captcha.siteKey=xxx`

Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe    
Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
    
![dev_captcha](https://user-images.githubusercontent.com/7373181/115413311-5a5c7400-a1f5-11eb-90ab-9aa2a0969404.png)

**Comment by yvesgoupil** [comment]
### GenerateSPConfFiles.zip compilation error

This problem needs to be investigated.

**Comment by yvesgoupil** [comment]
### populateLDAP.sh issue

There is likely a problem with the security-service. The admin user creation done with populateLDAP.sh needs a fully operationnal openwis securityservice.
A workaround is to create the first openwis admin user directly in the ldap with a script provided by Akka.

Copy AddUsers.sh and user.template in ~opendj/bin/ and modify AddUsers.sh according your configuration.

[addUsers2Ldap.tar.gz](https://github.com/OpenWIS/openwis/files/6344521/addUsers2Ldap.tar.gz)

**Comment by mgiannoni** [comment]
## populateLDAP.sh Issue:

### Additional LDAP Schemas

Several additional LDAP Schema's appear in 3.15:

1. SchemaMFA.ldif
2. SchemaOpenWIS.ldif

`ldapmodify -h localhost -p 4444 -D "cn=Directory Manager" -w "*******" -a -X --useSSL -f openwis-securityservice/openwis-securityservice-war/src/main/config/SchemaOpenWIS.ldif`

` ldapmodify -h localhost -p 4444 -D "cn=Directory Manager" -w "*******" -a -X --useSSL -f openwis-securityservice/openwis-securityservice-war/src/main/config/SchemaMFA.ldif
`

### Still Not Working

After adding the new schema, there still exists an error with the **OpenWISLastLoginTimestamp** attribute.

Entry **uid=admin,ou=people,dc=opensso,dc=java,dc=net** violates the Directory Server schema configuration because it includes attribute **OpenWISLastLoginTimestamp** which is not allowed by any of the objectclasses defined in that entry

**Comment by hacenesh** [comment]
In the commit f4bc771 we : 

- modified the SchemaOpenWIS.ldif to include OpenWISLastLoginTimestamp attribute. 
- removed SchemaMFA.ldif which is not used 
- modified UserManagementServiceImpl.java to include additional attributes in a user obj

Tested with @yvesgoupil => worked

**Comment by mgiannoni** [comment]
### UserManagementServiceImpl.java

I do not see a commit for the modifications to **UserManagementServiceImpl.java**.

**Comment by hacenesh** [comment]
The modification was in the privions commit 
https://github.com/OpenWIS/openwis/commit/fc2f8ea020c2b83d23053d5edccd6a4ad9eee67b

**Comment by mgiannoni** [comment]
### Please Improve Commit Headings

Please place the name of the file modified in the commit heading or comment so that changes can be located in the commit history.  The commit containing the modifications to **UserManagementServiceImpl.java** only displays the file **SchemaMFA.ldif**

**Comment by mgiannoni** [comment]
### Still Does Not Work


Please provide detailed instructions for fixing this issue.  


Initialize Deployment:
Deployment Name:
GISCTest
Administrator Login:
admin
Administrator Password:
"............."
Administrator Email:
openwis@openwis-ng.mdl.nws.noaa.gov
Administrator First name:
Joe
Administrator Last name:
Administrator
org.openwis.securityservice.UserManagementException_Exception: Entry uid=admin,ou=people,dc=opensso,dc=java,dc=net violates the Directory Server schema configuration because it includes attribute **OpenWISLastLoginTimestamp** which is not allowed by any of the objectclasses defined in that entry
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy35.initialize(Unknown Source)
	at org.openwis.usermanagement.PopulateUser.initializeDeployment(PopulateUser.java:158)
	at org.openwis.usermanagement.PopulateUser.displayMenu(PopulateUser.java:46)
	at org.openwis.usermanagement.PopulateUser.main(PopulateUser.java:239)

**Comment by yvesgoupil** [comment]
### USERS table update
For the moment, in order to perform the login process, the postgresql "USERS" table from OpenWIS db has to be manually modified:

`ALTER TABLE users ADD lastlogin timestamp without time zone;
ALTER TABLE users ADD lastpasswordchange timestamp without time zone;
update users set lastlogin='2021-05-06 13:15:38.05'  where id='1';
ALTER TABLE users ALTER COLUMN lastlogin set NOT NULL;

**Check :**
OpenWIS=> select id, username, password, surname, name, profile, lastlogin, lastpasswordchange from users;
And:
OpenWIS=> \d users;`

The fix will be pushed soon on github.

**Comment by yvesgoupil** [comment]
### Emails diffusion issue: 

The functionality of sending emails has been deported to an Amazon service, we must re-integrate it in 3.15 version for a good operation of a GISC or a DCPC.

**Comment by yvesgoupil** [comment]
Marc, 
1. I checked the last ldap schema commited by Hacene (fc2f8ea020) and it's the same that I'm using:
 openwis/openwis-securityservice/openwis-securityservice-war/src/main/config/SchemaOpenWIS.ldif .

2. You need to build the openwis-securityservice.war and deploy it again in tomcat in order to apply the fix done in UserManagementServiceImpl.java . One line is added:
579         user.setSecretKey("ATTRIBUTE_NOT_USED");

On the other hand, there is a difference with my file UserManagementServiceImpl.java, there is no change on my side at the line 74:
74             SECRET_KEY, LAST_LOGIN_TIME,

Could test the securityservice without "LAST_LOGIN_TIMESTAMP," added line 74?

**Comment by yvesgoupil** [comment]
### Update to openwis-metadataportal.properties" file

User and Admin portal:
There is a missing property in the "openwis-metadataportal.properties" file.

Add at the end of "openwis-metadataportal.properties" file:
openwis.metadataportal.idp.name=@idp_name@

It will be pushed on Github soon.

**Comment by yvesgoupil** [comment]
### Update to "openwis-metadataportal.properties" file

User and Admin portal:
There is a missing property in the "openwis-metadataportal.properties" file.

Add at the end of "openwis-metadataportal.properties" file:
**openwis.metadataportal.idp.name=@idp_name@**

The property for idp url must be entered also:
openwis.metadataportal.idp.url=http://@openam-server@/openam

It will be pushed on Github soon.

**Comment by yvesgoupil** [comment]
### User creation from admin portal Error
If I try to create a user from the admin portal (the admin user is "admin4"), there is an error msg displayed on the user creation windows.

In admin portal openwis.log
`2021-05-31 13:04:42,750 ERROR [openwis.util] - User: admin4. Unable to load credentials from service endpoint`

In SecurityService log:
`2021-05-31 13:36:04,428 ERROR [org.openwis.usermanagement.UtilEntry] - LDAP Exception : The object uid=yves.goupil,ou=people,dc=opensso,dc=java,dc=netdoesn't exist
2021-05-31 13:36:04,430 INFO  [org.openwis.usermanagement.UserManagementServiceImpl] - Creating User yves.goupil in Centre GiscDev
2021-05-31 13:36:04,440 INFO  [org.openwis.usermanagement.UserManagementServiceImpl] - Adding User yves.goupil to Group GiscDev / DEFAULT`

The user is created but does not allow authentication.

In ~/openam/openama/log/authentication.csv ,log:
`
"db4e9c12-7dbd-4668-a580-a166cb80cabe-6253649";"2021-05-31T13:51:54.944Z";"AM-LOGIN-MODULE-COMPLETED";"db4e9c12-7dbd-4668-a580-a166cb80cabe-6253647";"id=yves.goupil,ou=user,dc=openam,dc=openidentityplatform,dc=org";"[""8d8aabd7ef5a660701""]";"FAILED";"[""yves.goupil""]";;"[{""moduleId"":""DataStore"",""info"":{""authControlFlag"":""REQUIRED"",""moduleClass"":""DataStore"",""ipAddress"":""172.xx.xx.xx"",""authLevel"":""0""}}]";"Authentication";"/" 
`

**Comment by yvesgoupil** [comment]
### Self-registration missing on user  portal
Even if the self-registration option (System > System Configuration) is checked in the admin portal(screenshot below), the self-registration button is missing on the home page of the user portal.
When using a GISC, this option is necessary.
![2021-05-31_self_registration_option](https://user-images.githubusercontent.com/7373181/120212411-42373600-c232-11eb-8014-f69c5713ec29.png)
