### ISSUE TITLE
3.16 - Self register Error

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#403]
Self register fails.
- Log error on the user portal (logs/openwis.log)
`2022-11-25 11:43:45,890 INFO  [jeeves.request] - ==========================================================
2022-11-25 11:43:45,890 INFO  [jeeves.request] - HTML Request (from 172.24.248.25) : /openwis-user-portal/srv/en/user.register.submit
2022-11-25 11:43:45,891 INFO  [jeeves.service] - Dispatching : user.register.submit
2022-11-25 11:43:45,903 INFO  [openwis.selfRegister] - Self-registration: username=y.test1@yopmail.com, firstName=y, lastName=test1
2022-11-25 11:43:45,937 ERROR [jeeves.service] - Exception when executing service
2022-11-25 11:43:45,937 ERROR [jeeves.service] -  (C) Exc : javax.xml.ws.soap.SOAPFaultException: Attribute value cannot be null
javax.xml.ws.soap.SOAPFaultException: Attribute value cannot be null
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:118)
	at com.sun.proxy.$Proxy59.createUser(Unknown Source)
	at org.openwis.metadataportal.kernel.user.UserManager.createUser(UserManager.java:119)
	at org.openwis.metadataportal.services.register.SelfRegister.exec(SelfRegister.java:86)
	at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:243)
	at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:148)
	at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:500)
	at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
	at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
	at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-11-25 11:43:45,937 ERROR [jeeves.service] - Raised exception while executing service
javax.xml.ws.soap.SOAPFaultException: Attribute value cannot be null
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:189)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:122)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:118)
	at com.sun.proxy.$Proxy59.createUser(Unknown Source)
	at org.openwis.metadataportal.kernel.user.UserManager.createUser(UserManager.java:119)
	at org.openwis.metadataportal.services.register.SelfRegister.exec(SelfRegister.java:86)
	at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:243)
	at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:148)
	at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:500)
	at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:619)
	at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:189)
	at jeeves.server.sources.http.JeevesServlet.doPost(JeevesServlet.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-11-25 11:43:45,937 INFO  [jeeves.service] -    -> dispatching to error for : user.register.submit
2022-11-25 11:43:45,946 INFO  [jeeves.service] -      -> end error transformation for : user.register.submit
2022-11-25 11:43:45,946 INFO  [jeeves.service] -    -> error ended for : user.register.submit
2022-11-25 11:44:12,813 INFO  [jeeves.request] - ==========================================================`

- log error on OpenAM server (logs/openwis_security_service.log):
`2022-11-25 11:43:45,928 ERROR [org.openwis.usermanagement.UtilEntry] - LDAP Exception : The object uid=y.test1@yopmail.com,ou=people,dc=opensso,dc=java,dc=netdoesn't exist
2022-11-25 11:43:45,932 INFO  [org.openwis.usermanagement.UserManagementServiceImpl] - Creating User y.test1@yopmail.com in Centre GiscDev
2022-11-25 11:43:45,935 WARN  [org.apache.cxf.phase.PhaseInterceptorChain] - Application {http://securityservice.openwis.org/}UserManagementService#{http://securityservice.openwis.org/}createUser has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Attribute value cannot be null
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.createFault(AbstractJAXWSMethodInvoker.java:272)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:237)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:69)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:75)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$2.run(ServiceInvokerInterceptor.java:126)
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:131)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Attribute value cannot be null
	at com.novell.ldap.LDAPAttribute.<init>(Unknown Source)
	at org.openwis.usermanagement.UserManagementServiceImpl.createUser(UserManagementServiceImpl.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
	... 42 more`

**Comment by yvesgoupil** [comment]
After a testing the recent commit https://github.com/OpenWIS/openwis/commit/cb6c7822d233bc26d9757da985f7cac4e478e592 of December 7th , the self-registration is ok.

**Comment by yvesgoupil** [comment]
The mail workflow using SMTP must be tested.

**Comment by abrmh** [comment]
The issue is caused because of the missing  user.setSecretKey , it  should  be  added in class SelfRegister.java
the following commit soles the issue  **commit cb6c7822d233bc26d9757da985f7cac4e478e592**

**Comment by yvesgoupil** [comment]
The email sending at user creation using the self-registration on the user portal is done correctly.
It remains to test the sending of mail to the user in case of exceeding the quotas and the sending of mail to the administrator for the request of higher privileges.

**Comment by yvesgoupil** [comment]
All the tests are ok.I set the label to "Close me".

Yves.
