### ISSUE TITLE
Need a better timeout mechanism on socketRead

### ISSUE THREAD

**Issue by ywang-bom** [OpenWIS/openwis#84]
Synchronistation jobs can sometimes hang for unreasonably long time (serveral days). It would be helpful to implement a better timeout mechanism to terminate the job earlier and allow it to have a chance to restart in the next schedule. 

Since the jobs are scheduled to run every 24 hours, the upper-limit of the timeout shall not be longer than that. In practice, if no data is comming from a connection in the first few minutes, it is very likely the data will not come at all.

The stack dump is as follows:

```
"pool-7-thread-4" prio=10 tid=0x086aa800 nid=0x3327 runnable [0xa36d1000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:129)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:237)
        - locked <0xbd2f8af8> (a java.io.BufferedInputStream)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:77)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:105)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1115)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1832)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1590)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:995)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
        at org.fao.oaipmh.requests.Transport.doExecute(Transport.java:257)
        at org.fao.oaipmh.requests.Transport.execute(Transport.java:194)
        at org.fao.oaipmh.requests.AbstractRequest.sendRequest(AbstractRequest.java:92)
        at org.fao.oaipmh.requests.ListRecordsRequest.execute(ListRecordsRequest.java:63)
        at org.fao.oaipmh.requests.ListRecordsRequest.execute(ListRecordsRequest.java:37)
        at org.openwis.metadataportal.kernel.harvest.oaipmh.OaipmhHarvester.harvest(OaipmhHarvester.java:156)
        at org.openwis.metadataportal.kernel.harvest.exec.HarvesterRunnable.run(HarvesterRunnable.java:78)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by lmika-bom** [comment]
May not be worth doing this late in v3 life-cycle, but worth looking to see if this may still be a problem in OpenWIS 4.  Maybe GN has addressed it.  If not, this may be something that we can contribute back as I'm sure we wouldn't be the only ones this happens to.

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#44

**Comment by woollattd** [comment]
reopened since OpenWIS v3.x is in maintenance mode for next 6 years so this still applies
